baseurl = "https://lmt.sarahfinley.com/"
languageCode = "en-us"
title = "Sarah Finley - Licensed Massage Therapist"
theme = "hugo-creative-theme"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Sarah Finley - Licensed Massage Therapist"
	description = "Sarah Finley is a licensed massage therapist in the Idaho Falls, Idaho area.  Let her put her experience to work for you and your back, legs, feed, and neck."

	# The path must be relative to the static folder
	favicon = "favicon.png"

    font_awesome_kit = "18869afe50"



	# Navigation
	[params.navigation]
		brand = "Sarah Finley LMT"

		[params.navigation.links]
			about     = "About"
			services  = "Services"
			portfolio = "Reviews"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Comfort, Recovery, Relaxation, Wellness"
		subtitle   = "Sarah Finley - Licensed Massage Therapist in Idaho Falls, Idaho"
		buttonText = "Find out more"


	# About section
	[params.about]
		headline    = "Experience with Relaxing You"
		description = "\"Just the best massage I've ever had.\""
		#buttonText  = "Get started!"


	# Service section
	[params.services]
		headline = "At Your Service"

        [[params.services.list]]
            icon = "fa-hot-tub"
            title = "Comfort"
            description = "The solace of human warmth"

        [[params.services.list]]
			icon = "fa-medkit"
			title = "Recovery"
			description = "Medically-required massage"

		[[params.services.list]]
            icon = "fa-spa"
            title = "Relaxation"
            description = "A break from life"

        [[params.services.list]]
            icon = "fa-heart"
            title = "Wellness"
            description = "Support your mental and physical well-being"


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	#[params.aside]
	#	headline = "Get the Creative Theme for Hugo"

	#	[params.aside.button]
	#		text = "Download now"
	#		link = "//github.com/digitalcraftsman/hugo-creative-theme"

	# Contact section
	[params.contact]
		headline = "Schedule Your Appointment Today!"
		description = "Ready to become Sarah's next relaxed client?  Give us a call or send us an email and we will get back to you as soon as possible!"
		phone = "208-261-2325"
		email = "sarahfinleylmt@gmail.com"

	[params.acknowledgements]
        headline = "Acknowledgments:"

        [[params.acknowledgements.list]]
            text = "Budha header image - \"buddha\" by neonow - some rights reserved"
            link = "https://www.flickr.com/photos/neo-now/14081592055/"

        [[params.acknowledgements.list]]
            text = "Review Image - \"Spa Accents\" by Karl Cossio - some rights reserved"
            link = "https://www.flickr.com/photos/11507280@N03/5076738369/"

        [[params.acknowledgements.list]]
            text = "Review Image - \"Green Salt and Gel for Spa Treatments with Sea Stones on a Black Background\" by Maro Verch - some rights reserved"
            link = "https://foto.wuestenigel.com/green-salt-and-gel-for-spa-treatments-with-sea-stones-on-a-black-background/"

        [[params.acknowledgements.list]]
            text = "Review Image - \"Wet Black Stones\" by Maro Verch - some rights reserved"
            link = "https://foto.wuestenigel.com/wet-black-stones/"

        [[params.acknowledgements.list]]
            text = "Review Image - \"Waterfall\" by Chris Luczkow - some rights reserved"
            link = "https://www.flickr.com/photos/cluczkow/7687842854/"

        [[params.acknowledgements.list]]
            text = "Review Image - \"Whiteoak Canyon Trail Bridge\" by Bahahamelly - some rights reserved"
            link = "https://www.flickr.com/photos/bahahamelly/14900306241/"

        [[params.acknowledgements.list]]
            text = "Review Image - \"Tranquility\" by LadyDragonflyCC - some rights reserved"
            link = "https://www.flickr.com/photos/ladydragonflyherworld/6287757852/"

	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""
